{
  "openapi": "3.0.0",
  "info": {
    "title": "Binar Challenge Chapter 8",
    "description": "This is sample API Documentation for learning purpose",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:4000/api/v1"
    }
  ],
  "tags": [
    {
      "name": "Players",
      "description": "Endpoint Player"
    }
  ],
  "paths": {
    "/players": {
      "get": {
        "tags": [
          "Players"
        ],
        "summary": "Get All Players",
        "description": "Return List All Players",
        "parameters": [
          {
            "name": "username",
            "in": "query",
            "description": "username of the player",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "email",
            "in": "query",
            "description": "email of the player",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "experience",
            "in": "query",
            "description": "experience of the player",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "lvl",
            "in": "query",
            "description": "lvl of the player",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "535"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"217-oriCgHCpKIOt8nmeKSqypVnaUF4\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:08:10 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Player"
                },
                "example": {
                  "result": "Success",
                  "data": [
                    {
                      "id": 1,
                      "username": "PussySlayer613",
                      "email": "pussy.slay3r@gmail.com",
                      "password": "$2b$10$sVPYzKO2DFd4Bi2cddm2KO4q4ahh8mnTKUTIZmuT9VqQqjesHif7a",
                      "experience": 600000,
                      "lvl": 600,
                      "createdAt": "2023-06-27T07:53:10.797Z",
                      "updatedAt": "2023-06-27T07:53:10.797Z"
                    },
                    {
                      "id": 2,
                      "username": "HardcoreLevellingWarrior",
                      "email": "hclw@gmail.com",
                      "password": "$2b$10$e6Fy/LS.bt7LXTRv8XTWeOnfCY9e6SIJHw9RD.VR6CAqFzp4ztZIq",
                      "experience": 600000,
                      "lvl": 666,
                      "createdAt": "2023-06-27T07:53:10.870Z",
                      "updatedAt": "2023-06-27T07:53:10.870Z"
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Players"
        ],
        "summary": "Create New Player",
        "description": "Create new player and insert it into database",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "experience": {
                    "type": "integer"
                  }
                }
              },
              "example": {
                "username": "JohnDoe",
                "email": "johndoe@gmail.com",
                "password": "johndoe123",
                "experience": 0
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "260"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"104-ak7zOaJWXkcI9nz8BdGIUM2ZxEE\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:08:57 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Player"
                },
                "example": {
                  "result": "Success",
                  "data": {
                    "id": 3,
                    "username": "JohnDoe",
                    "email": "johndoe@gmail.com",
                    "password": "$2b$10$XlOiRNeS.hR3T5WJ/F8brO8LQRuiU61k6BMDRy3aI9B/A86UtA05K",
                    "experience": 0,
                    "lvl": 0,
                    "updatedAt": "2023-06-27T08:08:57.351Z",
                    "createdAt": "2023-06-27T08:08:57.351Z"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "62"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3e-xFTrp1qqvBEsH8ipn3pPOaXdCsM\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:09:23 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "result": "Failed",
                  "message": "username or email cannot empty"
                }
              }
            }
          }
        }
      }
    },
    "/players/{Id}": {
      "get": {
        "tags": [
          "Players"
        ],
        "summary": "Get Player By ID",
        "description": "Return player by specified ID",
        "parameters": [
          {
            "name": "Id",
            "in": "path",
            "description": "ID of player",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "279"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"117-Q+64kDuwWuOLcd1+tz4CB7uMwsw\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:12:35 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Player"
                },
                "example": {
                  "result": "Success",
                  "data": {
                    "id": 1,
                    "username": "PussySlayer613",
                    "email": "pussy.slay3r@gmail.com",
                    "password": "$2b$10$sVPYzKO2DFd4Bi2cddm2KO4q4ahh8mnTKUTIZmuT9VqQqjesHif7a",
                    "experience": 600000,
                    "lvl": 600,
                    "createdAt": "2023-06-27T07:53:10.797Z",
                    "updatedAt": "2023-06-27T07:53:10.797Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "59"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3b-ad6Le7QGGc1DJZL1oATasXgU65c\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:13:05 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "result": "Not found",
                  "message": "Player with (Id) not found"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Players"
        ],
        "summary": "Update Player By ID",
        "description": "Update player data by specified ID",
        "parameters": [
          {
            "name": "Id",
            "in": "path",
            "description": "ID of player",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "experience": {
                    "type": "integer"
                  }
                },
                "example": {
                  "username": "JohnDoe",
                  "email": "johndoe@gmail.com",
                  "password": "john123",
                  "experience": 100
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "71"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"47-tR/lbalqK95mGT0r8P/H1n2rYps\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:18:52 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "result": "Success",
                  "message": "Player with id: (Id) successfully updated"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "59"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3b-ad6Le7QGGc1DJZL1oATasXgU65c\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:20:07 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "result": "Not found",
                  "message": "Player with (Id) not found"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "48"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"30-lJ25iz8OnXX8wuG8CIN1xBMVba0\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:19:22 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "result": "failed",
                  "message": "Failed to update"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Players"
        ],
        "summary": "Delete Player",
        "description": "Remove player in database by specified ID",
        "parameters": [
          {
            "name": "Id",
            "in": "path",
            "description": "ID of player",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "76"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"4c-pvafHu14v8BFQjwJkr0lblVkZws\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:26:50 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "result": "Success",
                  "message": "Player with id: (Id), was deleted successfully"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "91"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"5b-4Gb6KMtWbgB7HsutKXu8Zcr5k5Q\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:27:10 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "result": "FAILED",
                  "message": "Cannot delete Player with id=(Id). Maybe Player was not found!"
                }
              }
            }
          }
        }
      }
    },
    "/players/exp/{Id}": {
      "post": {
        "tags": [
          "Players"
        ],
        "summary": "Update Player Experience",
        "description": "Only update player experience by specified ID",
        "parameters": [
          {
            "name": "Id",
            "in": "path",
            "description": "ID of player",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "experience": {
                    "type": "integer"
                  }
                },
                "example": {
                  "exp": 100
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "94"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"5e-SE891y+fXij50O7GE/thncA37ac\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:23:18 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "result": "SUCCESS",
                  "message": "Player with id = (Id) gain (exp) experience. Total experience = (exp)"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "57"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"39-rpS6Jy2R2UX0m1RThLTzzgtXYoY\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:25:52 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "result": "Failed",
                  "message": "Exp field cannot be empty"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "59"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3b-ad6Le7QGGc1DJZL1oATasXgU65c\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Tue, 27 Jun 2023 08:23:37 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "result": "Not found",
                  "message": "Player with (Id) not found"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Player": {
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "experience": {
            "type": "integer"
          }
        }
      }
    }
  }
}